# https://aka.ms/yaml

trigger:
- master
pr:
- master

pool:
  vmImage: 'windows-latest'

steps:
- pwsh: Invoke-Pester *.Tests.ps1
  displayName: 'Run helper module tests'
  workingDirectory: '$(System.DefaultWorkingDirectory)/Modules/MathshammerHelper/Tests'

- task: PublishTestResults
  inputs:
    testResultsFormat: NUnit
    testResultsFiles: '**/TEST-*.xml' 

