# https://aka.ms/yaml

trigger:
- master
pr:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: coreVariables

steps:
- pwsh: ./runTests.ps1
  displayName: 'Run helper module tests'
  workingDirectory: '$(Build.SourcesDirectory)/Modules/MathshammerHelper/Tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: NUnit
    testResultsFiles: '**/TEST-*.xml'
    failTaskOnFailedTests: true
  condition: succeededOrFailed()

- task: AzurePowerShell@4
  displayName: 'Install terraform'
  inputs:
    azureSubscription: azure
    azurePowerShellVersion: latestVersion
    scriptType: FilePath
    scriptPath: '$(Build.SourcesDirectory)/infrastructure/Install-Terraform.ps1'
    scriptArguments: ''

