# https://aka.ms/yaml

trigger:
- master
pr:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- pwsh: Invoke-Pester *.Tests.ps1
  displayName: 'Run helper module tests'
  workingDirectory: Modules/MathshammerHelper/Tests


