# https://aka.ms/yaml

trigger:
- master
pr:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- pwsh: ./runTests.ps1
  displayName: 'Run helper module tests'
  workingDirectory: '$(Build.SourcesDirectory)/Modules/MathshammerHelper/Tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: NUnit
    testResultsFiles: '**/TEST-*.xml' 
  condition: succeededOrFailed()

