# https://aka.ms/yaml

trigger:
- master
pr:
- master

pool:
  vmImage: 'windows-latest'

steps:
- pwsh: Invoke-Pester -Script *.Tests.ps1 -OutputFormat NUnitXml -OutputFile 'TEST-HelperModule.xml'
  displayName: 'Run helper module tests'
  workingDirectory: '$(System.DefaultWorkingDirectory)/Modules/MathshammerHelper/Tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: NUnit
    testResultsFiles: '**/TEST-*.xml' 

