# https://aka.ms/yaml

trigger:
- master
pr:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: coreVariables

steps:
- pwsh: ./runTests.ps1
  displayName: 'Run helper module tests'
  workingDirectory: '$(Build.SourcesDirectory)/Modules/MathshammerHelper/Tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: NUnit
    testResultsFiles: '**/TEST-*.xml'
    failTaskOnFailedTests: true
  condition: succeededOrFailed()

- pwsh: '$(Build.SourcesDirectory)/infrastructure/Install-Terraform.ps1'
  displayName: 'Install terraform'

#- task: AzureCLI@1
#  displayName: 'terraform apply'
#  inputs:
#    azureSubscription: azure
#    azurePowerShellVersion: latestVersion
#    scriptType: FilePath
#    scriptPath: '$(Build.SourcesDirectory)/infrastructure/Invoke-Terraform.ps1'
#    scriptArguments: -Path '$(Build.SourcesDirectory)/infrastructure/terraform'

- task: AzureCLI@1
  inputs:
    azureSubscription: azure
    scriptLocation: 'scriptPath'
    scriptPath: '$(Build.SourcesDirectory)/infrastructure/runTerraform.sh'
    arguments: '$(Build.SourcesDirectory)/infrastructure/terraform'
